apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-crds
  namespace: argocd
spec:
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: agentgateway-crds
    helm:
      skipCrds: false
    repoURL: cr.agentgateway.dev/charts
    targetRevision: v1.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
