apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-controller
  namespace: argocd
spec:
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: agentgateway
    helm:
      skipCrds: false
      parameters:
        - name: controller.image.pullPolicy
          value: "Always"
        - name: controller.extraEnv.KGW_ENABLE_GATEWAY_API_EXPERIMENTAL_FEATURES
          value: "true"
    repoURL: cr.agentgateway.dev/charts
    targetRevision: v1.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
