apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-demo-app
  namespace: argocd
spec:
  destination:
    namespace: new-demo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/phuongpham247/new-demo-app.git
    targetRevision: main
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
