apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argocd
spec:
  destination:
    namespace: game-2048
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/phuongpham247/2048-app.git
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
